<a href="https://colab.research.google.com/github/SandeshBashyal/Pytorch_Learning/blob/main/Indexing_Fundamentals_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Indexing (Selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy.

In [1]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [3]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [4]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [5]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1] # used semicolon so the output is [5]

tensor([5])

In [6]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [7]:
x[0,0]

tensor([1, 2, 3])

In [8]:
# index on x to return 9
print(x[0][2][2])
print(x[:, 2, 2])

tensor(9)
tensor([9])


In [9]:
# index to return 3, 6, 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [10]:
# NumPy array to tensor
import torch
import numpy as np

array = np. arange(1., 8.)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [11]:
array.dtype

dtype('float64')

In [12]:
torch.arange(1., 8.).dtype

torch.float32

numpy default datatype is float64 while pytorch default datatype is float32

In [13]:
# Let's change datatype
tensor32 = torch.from_numpy(array).type(torch.float32)
array, tensor32, tensor32.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [14]:
# Change the value of array, what will this do to `tensor`?
array = array +1
array, tensor, tensor32
# doesn't change the value of tensor as tensor is given new original memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [15]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # numpy is assigned float32 as the default of pytorch

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [16]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor +1
tensor, numpy_tensor
# numpy_tensor doesn't change

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations-> update random numbers to try and
make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch coms the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [17]:
# Generated randomness
torch.rand(3, 3) # random numbers again and again

tensor([[0.7976, 0.8920, 0.5866],
        [0.1549, 0.6269, 0.0924],
        [0.2491, 0.1286, 0.7603]])

In [18]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2840, 0.4506, 0.4174, 0.3070],
        [0.2280, 0.0733, 0.7836, 0.5089],
        [0.3670, 0.1507, 0.6403, 0.9264]])
tensor([[0.7846, 0.2268, 0.1121, 0.5410],
        [0.5712, 0.7007, 0.6250, 0.0898],
        [0.4020, 0.6121, 0.4504, 0.3882]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [19]:
# Let's make some random but reproducible tensors
# wikipedia and documentation
import torch
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # one block of code in notebooks
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - needs setup and requires the investment of purchasing a GPU ->https://timdettmers.com/category/deep-learning/
3. Cloud Computing - GCP, AWS, Azure

For 2, 3, needs setup, so visit in documentation

Go to runtime -> Change runtime type -> Hardware accelerator -> GPU -> Save

In [20]:
!nvidia-smi

Tue May 16 03:31:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [21]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's available of running compute on GPU or CPU,
it's best practice to setup device agnostic code:
https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code

E.g. run of GPU if available, else default to CPU

In [22]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [23]:
# Count no of devices
torch.cuda.device_count()

1

### 3. Putting tensors and Models on GPU

The reason we want our tensors/ models on the GPU is because using a GPU results in faster computations.

In [24]:
# Create a tensor (default on the CPU)
import torch
tensor = torch.tensor([1, 2, 3]) # device = "cuda"

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [25]:
# Move tensor to GPU, if available
import torch
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [26]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [27]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [28]:
tensor_on_gpu # it remains unchanged

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra - Cirriculum
Exercises: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
Extra-Cirriculum : https://www.learnpytorch.io/00_pytorch_fundamentals/#extra-curriculum