<a href="https://colab.research.google.com/github/SandeshBashyal/Pytorch_Learning/blob/main/Intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Documentation
Link: https://pytorch.org/docs/stable/index.html

In [1]:
import torch    
torch.__version__

'2.0.0+cu118'

## Introduction to tensors
  Tensors are main building blocks of deep learning in general, or data. It is an algebraic object that describes a multilinear relationship betn sets of algebraic objects related to a vector space.

## Creating Tensors
  Pytorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Scalar Dimensions
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Vector Dimensions
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR[0, 1]

tensor([3, 6, 9])

In [18]:
TENSOR[0, 2, 2]

tensor(5)

### Random tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [19]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4678, 0.9027, 0.7597, 0.7227],
        [0.8881, 0.3186, 0.2403, 0.1611],
        [0.2675, 0.6111, 0.5721, 0.8760]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #  color channel (R, G, B), height, width,
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
random_tensor = torch.rand(5, 10, 3)
random_tensor

tensor([[[0.3232, 0.8841, 0.8792],
         [0.2506, 0.7147, 0.9471],
         [0.6385, 0.7686, 0.8241],
         [0.1554, 0.4943, 0.5792],
         [0.6869, 0.8445, 0.2806],
         [0.4274, 0.7240, 0.7147],
         [0.4047, 0.5733, 0.5920],
         [0.8646, 0.7859, 0.3736],
         [0.3218, 0.3831, 0.7688],
         [0.4769, 0.5706, 0.5416]],

        [[0.6812, 0.8614, 0.6486],
         [0.6653, 0.4495, 0.0261],
         [0.1925, 0.1510, 0.8825],
         [0.1248, 0.3966, 0.3970],
         [0.5325, 0.6775, 0.3640],
         [0.8096, 0.7086, 0.3426],
         [0.0012, 0.9340, 0.4995],
         [0.9355, 0.9384, 0.5580],
         [0.6394, 0.2950, 0.3561],
         [0.8519, 0.3205, 0.9821]],

        [[0.3117, 0.5212, 0.3320],
         [0.8812, 0.5823, 0.5792],
         [0.2131, 0.2833, 0.8431],
         [0.8407, 0.8695, 0.6746],
         [0.4099, 0.1579, 0.1149],
         [0.3153, 0.3101, 0.2289],
         [0.8658, 0.2261, 0.8695],
         [0.2572, 0.6673, 0.2913],
         [0.5443

In [23]:
random_tensor.ndim

3

In [24]:
torch.rand(size=(3, 3))

tensor([[0.3590, 0.8347, 0.9577],
        [0.1345, 0.6212, 0.9574],
        [0.9857, 0.1903, 0.4883]])

# Zeors and Ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-28-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
one_to_ten = torch.arange(start= 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,  # float32, float16 according to precision
                               device = None, # what device is your tensor on : default will be cpu, for gpu it will be cuda
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors (Attributes)
Tensors not right datatype  - to do get datatype from a tensor, can use `tensor.dtype`

Tensors not right shape  - to get shape from a tensor, can use `tensor.shape`

Tensors not on the right device  - to get device froma tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8131, 0.8418, 0.6624, 0.6913],
        [0.1955, 0.1111, 0.7257, 0.3029],
        [0.8344, 0.5619, 0.7263, 0.8990]])

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.8131, 0.8418, 0.6624, 0.6913],
        [0.1955, 0.1111, 0.7257, 0.3029],
        [0.8344, 0.5619, 0.7263, 0.8990]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu
