<a href="https://colab.research.google.com/github/SandeshBashyal/Pytorch_Learning/blob/main/Manipulating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulating tensors (Tensor Operations)

Operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [1]:
import torch

In [2]:
# Create a tensor and add 10 to it 
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [3]:
# Multiply tensor by 10 
tensor *10

tensor([10, 20, 30])

In [4]:
tensor

tensor([1, 2, 3])

In [5]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [6]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # torch.add, torch.sub

tensor([10, 20, 30])

In [7]:
# Divide by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise Multiplication (Scalar)
2. Matrix Multiplication (Dot Product)

There are 2 main rules while performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match: (Columns of A = Rows of B)
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**: (Rows of A, Columns of B)
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

Try out the multiplication in: http://matrixmultiplication.xyz/

In [8]:
# Element Wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [9]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [10]:
# Matrix Multiplication by hand
1*1 + 2*2 + 3*3


14

In [11]:
### Code:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.5 ms, sys: 83 µs, total: 1.58 ms
Wall time: 1.49 ms


In [12]:
# Vectorization
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.33 ms, sys: 0 ns, total: 1.33 ms
Wall time: 1.39 ms


tensor(14)

In [13]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[3.1354, 2.0398, 2.8280],
        [2.4856, 1.9500, 2.5713],
        [2.5735, 1.5883, 2.1954]])

In [14]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3)).shape

torch.Size([3, 3])

### One of the most common errors in deep learning: shape errors

In [15]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul (it's an alias for writing less code)
# shape error
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of the tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [16]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [17]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [18]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [19]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [20]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @  {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @  torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
